version: '3'

services:
  phoenix:
    build: "."
    environment: 
      MIX_ENV: dev
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  postgres:
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tergeo
      POSTGRES_PASSWORD: tergeo
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: